import type {Metadata} from "next";

import React from "react";
import {buttonVariants} from "@/components/ui/button";
import {Menu} from "lucide-react";
import Link from "next/link";
import {cn} from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <section className={`flex flex-col h-screen bg-black text-white font-sans`}>

        {children}

        {/* Bottom navigation */}
        <div className="fixed justify-between items-center p-4 bg-zinc-900 w-full flex bottom-0">

          <Link
              href={`/`}
              className={
                cn(`flex flex-col items-center`,
                    buttonVariants({variant: 'ghost'}))
              }
          >
            <Menu className="h-6 w-6"/>
            <span className="text-xs mt-1">Home</span>
          </Link>

          <Link
              href={`/book`}
              className={
                cn(`flex flex-col items-center`,
                    buttonVariants({variant: 'ghost'}))
              }
          >
            <Menu className="h-6 w-6"/>
            <span className="text-xs mt-1">Bible</span>
          </Link>


          <Link
              href={`/more`}
              className={
                cn(`flex flex-col items-center`,
                    buttonVariants({variant: 'ghost'}))
              }
          >
            <Menu className="h-6 w-6"/>
            <span className="text-xs mt-1">More</span>
          </Link>
        </div>
      </section>
  );
}
